import React from 'react';
import { motion } from 'framer-motion';
import { 
  X, Printer, Download, FileText, CheckCircle2 
} from 'lucide-react';

interface ReportGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ReportGeneratorModal: React.FC<ReportGeneratorModalProps> = ({
  isOpen,
  onClose
}) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const reportText = `
================================================================================
EXECUTIVE RESEARCH REPORT: WSN ENERGY-EFFICIENT ROUTING & COVERAGE OPTIMIZATION
ANN-Based Active/Sleep Prediction + Multi-Objective PSO-Hybrid Routing
================================================================================

1. EXPERIMENTAL CONFIGURATION
- Deployment Area: 100m x 100m Field
- Total Sensors: 100 Heterogeneous Nodes (70% Normal 0.5J, 20% Adv 1.0J, 10% Super 1.5J)
- Base Station Coordinate: (50m, 150m)
- Sensing Radius: 10.0m | Communication Radius: 20.0m
- Simulation Horizon: 1000 Rounds
- Independent Seeds Evaluated: Seed 42, Seed 123, Seed 456

2. KEY VERIFIED PERFORMANCE BENCHMARKS (3-SEED AVERAGE)
- Active Sensor Nodes: 56.0 Nodes (-44.00% vs. Baseline 100)
- Sleeping Sensor Nodes: 44.0 Nodes (100% battery preserved)
- Sensing Coverage: 92.73% (Delta = -1.00%, strictly preserved within target)
- Sensing Overlap Ratio: 54.97% (-33.38% relative reduction from 82.51%)
- First Node Dead (FND): 425.33 Rounds (+194.01% increase from 144.67)
- Half Nodes Dead (HND): 1000.00 Rounds (+17.37% increase from 852.00)
- Simulation Execution Time: 128.06s (-49.32% runtime reduction from 252.69s)
- Delivered Throughput: 48,109 Packets (-32.73% intentional trade-off)

3. RESEARCH CONCLUSIONS
The proposed ANN + PSO-Hybrid framework successfully prolongs network stability by nearly 3-fold while preserving essential spatial sensing coverage and reducing redundant overlapping radio transmissions.
================================================================================
Generated by WSN Research Laboratory System
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'WSN_Research_Benchmark_Report.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div 
      className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4 sm:p-6 overflow-y-auto"
      onClick={onClose}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 15 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 15 }}
        className="bg-[#0D1626] rounded-3xl max-w-4xl w-full p-6 sm:p-8 border border-[#1C3150] shadow-2xl shadow-cyan-950/40 relative font-mono my-8"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex justify-between items-center pb-4 border-b border-[#1C3150] mb-6">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 bg-cyan-500/15 rounded-xl text-cyan-400 border border-cyan-500/30">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base sm:text-lg font-bold text-white tracking-wide">
                EXECUTIVE RESEARCH SUMMARY REPORT
              </h3>
              <span className="text-xs text-slate-400">
                Automated Academic Validation &amp; Milestone Audit
              </span>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="p-2 text-slate-300 hover:text-cyan-400 bg-[#0B1220] rounded-xl border border-[#1C3150] hover:border-cyan-500/40 transition-all text-xs flex items-center gap-1.5"
              title="Print Report"
            >
              <Printer className="w-4 h-4" />
              <span className="hidden sm:inline">Print</span>
            </button>
            <button
              onClick={handleDownload}
              className="p-2 text-slate-300 hover:text-cyan-400 bg-[#0B1220] rounded-xl border border-[#1C3150] hover:border-cyan-500/40 transition-all text-xs flex items-center gap-1.5"
              title="Download Text Report"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Download</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-white bg-[#0B1220] rounded-xl border border-[#1C3150] transition-all"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        <div className="space-y-6 text-xs text-slate-300 leading-relaxed max-h-[60vh] overflow-y-auto pr-2">
          <div className="bg-[#070B14] p-5 rounded-2xl border border-[#1C3150] space-y-2">
            <h4 className="text-sm font-bold text-cyan-400 uppercase tracking-wider">
              1. Executive Abstract &amp; Problem Statement
            </h4>
            <p className="font-sans text-slate-300 leading-relaxed text-xs sm:text-sm">
              In dense Wireless Sensor Networks (WSNs), excessive sensor overlap and uncoordinated cluster head (CH) selection rapidly deplete sensor battery reserves. This project implements a dual-stage optimization framework combining an <strong>Artificial Neural Network (MLPClassifier)</strong> for heuristic active/sleep node state prediction and a <strong>Multi-Objective Particle Swarm Optimization (PSO)</strong> algorithm for dynamic Cluster Head selection with intra-cluster PEGASIS chaining.
            </p>
          </div>

          <div className="space-y-2">
            <h4 className="text-sm font-bold text-blue-400 uppercase tracking-wider">
              2. Quantitative Experimental Verification (3-Seed Average)
            </h4>
            <div className="bg-[#070B14] rounded-xl border border-[#1C3150] overflow-hidden">
              <table className="w-full text-left text-xs font-mono">
                <thead>
                  <tr className="bg-[#0B1220] text-slate-300 uppercase text-[10px] border-b border-[#1C3150]">
                    <th className="py-2.5 px-4">Metric</th>
                    <th className="py-2.5 px-4">Baseline PSO-Hybrid</th>
                    <th className="py-2.5 px-4 text-cyan-400">Proposed ANN + PSO</th>
                    <th className="py-2.5 px-4">Relative Change</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#1C3150]/60">
                  <tr>
                    <td className="py-2.5 px-4 font-bold text-white">Active Sensor Nodes</td>
                    <td className="py-2.5 px-4 text-slate-400">100.0 Nodes</td>
                    <td className="py-2.5 px-4 text-cyan-300 font-bold">56.0 Nodes</td>
                    <td className="py-2.5 px-4 text-cyan-400 font-bold">-44.00%</td>
                  </tr>
                  <tr>
                    <td className="py-2.5 px-4 font-bold text-white">Sensing Coverage</td>
                    <td className="py-2.5 px-4 text-slate-400">93.73%</td>
                    <td className="py-2.5 px-4 text-cyan-300 font-bold">92.73%</td>
                    <td className="py-2.5 px-4 text-blue-400 font-bold">Δ = -1.00% (Within target)</td>
                  </tr>
                  <tr>
                    <td className="py-2.5 px-4 font-bold text-white">Sensing Overlap Ratio</td>
                    <td className="py-2.5 px-4 text-slate-400">82.51%</td>
                    <td className="py-2.5 px-4 text-cyan-300 font-bold">54.97%</td>
                    <td className="py-2.5 px-4 text-cyan-400 font-bold">-33.38% Redundancy Drop</td>
                  </tr>
                  <tr>
                    <td className="py-2.5 px-4 font-bold text-white">First Node Dead (FND)</td>
                    <td className="py-2.5 px-4 text-slate-400">144.67 Rnds</td>
                    <td className="py-2.5 px-4 text-emerald-400 font-bold">425.33 Rnds</td>
                    <td className="py-2.5 px-4 text-emerald-400 font-bold">+194.01% (Nearly 3x)</td>
                  </tr>
                  <tr>
                    <td className="py-2.5 px-4 font-bold text-white">Half Nodes Dead (HND)</td>
                    <td className="py-2.5 px-4 text-slate-400">852.00 Rnds</td>
                    <td className="py-2.5 px-4 text-emerald-400 font-bold">1000.00 Rnds</td>
                    <td className="py-2.5 px-4 text-emerald-400 font-bold">+17.37% (Reached Limit)</td>
                  </tr>
                  <tr>
                    <td className="py-2.5 px-4 font-bold text-white">Simulation Runtime</td>
                    <td className="py-2.5 px-4 text-slate-400">252.69 s</td>
                    <td className="py-2.5 px-4 text-cyan-300 font-bold">128.06 s</td>
                    <td className="py-2.5 px-4 text-cyan-400 font-bold">-49.32% Execution Speedup</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div className="p-4 bg-[#070B14] rounded-xl border border-[#1C3150] flex items-center justify-between text-xs">
            <div className="flex items-center space-x-2">
              <CheckCircle2 className="w-4 h-4 text-cyan-400" />
              <span className="text-white font-bold">Statistically Validated across Seeds 42, 123, 456</span>
            </div>
            <span className="text-slate-500">WSN Intelligence Research Lab</span>
          </div>
        </div>
      </motion.div>
    </div>
  );
};
